sudo: required
services:
  - docker

before_install:
  - docker build -t alex067/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run alex067/react-test npm test -- --coverage

after_success:
  - docker build -t alex067/multi-client ./client
  - docker build -t alex067/multi-nginx ./nginx
  - docker build -t alex067/multi-server ./server
  - docker build -t alex067/multi-worker ./worker
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alex067/multi-client
  - docker push alex067/multi-nginx
  - docker push alex067/multi-server
  - docker push alex067/multi-worker

